### ISSUE TITLE
I have a question on earth-reverse-engineering-utils

### ISSUE THREAD

**Issue by Grisoulechat** [LexSong/lego-world-map-markley#2]
I have a question on earth-reverse-engineering-utils
Where can I chat with you?
Thanks

**Comment by LexSong** [comment]
Hi, the original [earth-reverse-engineering](https://github.com/retroplasma/earth-reverse-engineering) and my repo are both achieved. It's provided as it is and I'm no longer working on it. Using `@LexSong` in your fork's issues to ask question and I may help you there.
